package com.model;
// Generated Oct 10, 2023 9:05:01 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Book generated by hbm2java
 */

@Entity
@Table (name="book", catalog = "book")

public class Book  implements java.io.Serializable {


     public Integer id;
     private String title;
     private String preview;
     private String writer;
     private Date releaseDate;
     private String link;

    public Book() {
    }

    public Book(String title, String preview, String writer, Date releaseDate, String link) {
       this.title = title;
       this.preview = preview;
       this.writer = writer;
       this.releaseDate = releaseDate;
       this.link = link;
    }
   @Id @GeneratedValue(strategy = GenerationType.AUTO)
   @Column(name ="id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPreview() {
        return this.preview;
    }
    
    public void setPreview(String preview) {
        this.preview = preview;
    }
    public String getWriter() {
        return this.writer;
    }
    
    public void setWriter(String writer) {
        this.writer = writer;
    }
    public Date getReleaseDate() {
        return this.releaseDate;
    }
    
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }




}


